# Generated by Django 4.2.4 on 2023-09-20 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessoes',
            name='faltas',
            field=models.ManyToManyField(blank=True, default='', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessoes',
            name='localformacao',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='localformacao'),
        ),
        migrations.AlterField(
            model_name='sessoes',
            name='sumario',
            field=models.TextField(blank=True, default='', max_length=400, verbose_name='localformacao'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='publicoalvo',
            field=models.CharField(default='Professores do ensino básico e secundário', max_length=80, null=True, verbose_name='publico alvo'),
        ),
    ]
